return {
	Title = "过月同道商人自动采购",
	Version = "0.5.0.0",
	BackendPlugins = {
		[1] = "AutoMonthlyGroupMerchantBuy.dll",
	},
	Author = "Codex",
	GameVersion = "1.0.56.0",
	Source = 0,
	Description = "过月时扫描太吾同道中的商人，并自动购买食材、药材与毒物。\r\n可以设置购买材料的品级范围，以及触发自动购买的钱和负重阈值。\r\n为避免爆仓，默认设置为自动购买到私库，也可以改成行囊或者公库。\r\n\r\n\r\nv0.2：\r\n新增功能，会自动检测行囊上限，不会因自动购买超重；\r\n也支持直接购买到私库或者公库，不受地格限制，更方便，不会爆仓了。\r\n\r\nv0.3：\r\n支持热修改，修改配置后不用重启游戏了；\r\n同时优化了配置页面\r\n\r\nv0.4：\r\n支持不同材料单独设置品级\n\nv0.5：\n适配新购买接口，解决爆红",
	NeedRestartWhenSettingChanged = false,
	SettingGroups = {
		[1] = "基础设置",
		[2] = "高级设置",
		[3] = "品级设置",
		[4] = "调试设置",
	},
	DefaultSettings = {
		[1] = {
			SettingType = "Toggle",
			Key = "EnableAutoMonthlyBuy",
			DisplayName = "启用过月自动采购",
			Description = "过月时自动从同道中的商人处购买符合设置的材料。",
			GroupName = "基础设置",
			DefaultValue = true,
		},
		[2] = {
			SettingType = "Toggle",
			Key = "BuyFoodMaterial",
			DisplayName = "采购食材",
			Description = "允许自动采购食材类材料。",
			GroupName = "基础设置",
			DefaultValue = true,
		},
		[3] = {
			SettingType = "Toggle",
			Key = "BuyMedicinalMaterial",
			DisplayName = "采购药材",
			Description = "允许自动采购药材类材料。",
			GroupName = "基础设置",
			DefaultValue = true,
		},
		[4] = {
			SettingType = "Toggle",
			Key = "BuyPoisonMaterial",
			DisplayName = "采购毒物",
			Description = "允许自动采购毒物类材料。",
			GroupName = "基础设置",
			DefaultValue = true,
		},
		[5] = {
			SettingType = "Toggle",
			Key = "SkipPriceIncreasedItems",
			DisplayName = "不采购涨价物品",
			Description = "开启后跳过涨价商品。",
			GroupName = "基础设置",
			DefaultValue = false,
		},
		[6] = {
			SettingType = "Toggle",
			Key = "SkipOriginalPriceItems",
			DisplayName = "不采购原价物品",
			Description = "开启后跳过原价商品。",
			GroupName = "基础设置",
			DefaultValue = false,
		},
		[7] = {
			SettingType = "Dropdown",
			Key = "TargetItemSource",
			DisplayName = "默认保存位置",
			Description = "选择自动采购物品的保存位置。只有选择行囊时才会启用背包负重预留保护。",
			GroupName = "基础设置",
			Options = {
				[1] = "行囊",
				[2] = "私库",
				[3] = "公库",
			},
			DefaultValue = 1,
		},
		[8] = {
			SettingType = "Slider",
			Key = "AutoBuyMoneyThreshold",
			DisplayName = "自动采购银币阈值",
			Description = "仅当当前携带银币高于该数值时，过月自动采购才会触发。",
			GroupName = "高级设置",
			MinValue = 0,
			MaxValue = 100000,
			StepSize = 5000,
			DefaultValue = 20000,
		},
		[9] = {
			SettingType = "Slider",
			Key = "InventoryLoadReserve",
			DisplayName = "背包负重预留阈值",
			Description = "自动采购后背包负重不会超过上限减去该预留值。仅保存到行囊时生效。",
			GroupName = "高级设置",
			MinValue = 0,
			MaxValue = 20,
			StepSize = 1,
			DefaultValue = 10,
		},
		[10] = {
			SettingType = "Dropdown",
			Key = "FoodHighestPurchaseGrade",
			DisplayName = "食材最高品级",
			Description = "自动采购食材时允许购买的最高品级。",
			GroupName = "品级设置",
			Options = {
				[1] = "神·一品",
				[2] = "绝·二品",
				[3] = "超·三品",
				[4] = "极·四品",
				[5] = "秘·五品",
				[6] = "奇·六品",
				[7] = "上·七品",
				[8] = "中·八品",
				[9] = "下·九品",
			},
			DefaultValue = 0,
		},
		[11] = {
			SettingType = "Dropdown",
			Key = "FoodLowestPurchaseGrade",
			DisplayName = "食材最低品级",
			Description = "自动采购食材时允许购买的最低品级。",
			GroupName = "品级设置",
			Options = {
				[1] = "神·一品",
				[2] = "绝·二品",
				[3] = "超·三品",
				[4] = "极·四品",
				[5] = "秘·五品",
				[6] = "奇·六品",
				[7] = "上·七品",
				[8] = "中·八品",
				[9] = "下·九品",
			},
			DefaultValue = 8,
		},
		[12] = {
			SettingType = "Dropdown",
			Key = "MedicinalHighestPurchaseGrade",
			DisplayName = "药材最高品级",
			Description = "自动采购药材时允许购买的最高品级。",
			GroupName = "品级设置",
			Options = {
				[1] = "神·一品",
				[2] = "绝·二品",
				[3] = "超·三品",
				[4] = "极·四品",
				[5] = "秘·五品",
				[6] = "奇·六品",
				[7] = "上·七品",
				[8] = "中·八品",
				[9] = "下·九品",
			},
			DefaultValue = 3,
		},
		[13] = {
			SettingType = "Dropdown",
			Key = "MedicinalLowestPurchaseGrade",
			DisplayName = "药材最低品级",
			Description = "自动采购药材时允许购买的最低品级。",
			GroupName = "品级设置",
			Options = {
				[1] = "神·一品",
				[2] = "绝·二品",
				[3] = "超·三品",
				[4] = "极·四品",
				[5] = "秘·五品",
				[6] = "奇·六品",
				[7] = "上·七品",
				[8] = "中·八品",
				[9] = "下·九品",
			},
			DefaultValue = 5,
		},
		[14] = {
			SettingType = "Dropdown",
			Key = "PoisonHighestPurchaseGrade",
			DisplayName = "毒物最高品级",
			Description = "自动采购毒物时允许购买的最高品级。",
			GroupName = "品级设置",
			Options = {
				[1] = "神·一品",
				[2] = "绝·二品",
				[3] = "超·三品",
				[4] = "极·四品",
				[5] = "秘·五品",
				[6] = "奇·六品",
				[7] = "上·七品",
				[8] = "中·八品",
				[9] = "下·九品",
			},
			DefaultValue = 3,
		},
		[15] = {
			SettingType = "Dropdown",
			Key = "PoisonLowestPurchaseGrade",
			DisplayName = "毒物最低品级",
			Description = "自动采购毒物时允许购买的最低品级。",
			GroupName = "品级设置",
			Options = {
				[1] = "神·一品",
				[2] = "绝·二品",
				[3] = "超·三品",
				[4] = "极·四品",
				[5] = "秘·五品",
				[6] = "奇·六品",
				[7] = "上·七品",
				[8] = "中·八品",
				[9] = "下·九品",
			},
			DefaultValue = 5,
		},
		[16] = {
			SettingType = "Toggle",
			Key = "EnableDebugLogging",
			DisplayName = "Debug Logging",
			Description = "Enable verbose per-item logs for troubleshooting auto purchase results.",
			GroupName = "调试设置",
			DefaultValue = false,
		},
	},
	TagList = {
		[1] = "Optimizations",
		[2] = "Compatible Mods",
	},
	Visibility = 0,
	ChangeConfig = false,
	HasArchive = false,
	FileId = 3750930153,
	UpdateLogList = {
		[1] = {
			Timestamp = 1783710189,
		},
	},
	Cover = "v4_1.png",
	WorkshopCover = "v4_1.png",
	DetailImageList = {
		[1] = "v5.png",
	},
}
